// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIUc1owmSEPVdDFOiEnIurgipIBt4vCz8',
    appId: '1:463099747442:web:0c4cdf9da93e78a99a76eb',
    messagingSenderId: '463099747442',
    projectId: 'chatapp-7ceab',
    authDomain: 'chatapp-7ceab.firebaseapp.com',
    storageBucket: 'chatapp-7ceab.appspot.com',
    measurementId: 'G-MKRNXP1NRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFtJDNxVFNTB0RIwoB1Clud6Fi1_VYSec',
    appId: '1:463099747442:android:86efa706a6af3d099a76eb',
    messagingSenderId: '463099747442',
    projectId: 'chatapp-7ceab',
    storageBucket: 'chatapp-7ceab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdwEqrG2aCzxwFnsSrNNe0o6B-Yl7Lp-w',
    appId: '1:463099747442:ios:f1f637bc7315de729a76eb',
    messagingSenderId: '463099747442',
    projectId: 'chatapp-7ceab',
    storageBucket: 'chatapp-7ceab.appspot.com',
    iosBundleId: 'com.example.chatapp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdwEqrG2aCzxwFnsSrNNe0o6B-Yl7Lp-w',
    appId: '1:463099747442:ios:f1f637bc7315de729a76eb',
    messagingSenderId: '463099747442',
    projectId: 'chatapp-7ceab',
    storageBucket: 'chatapp-7ceab.appspot.com',
    iosBundleId: 'com.example.chatapp.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIUc1owmSEPVdDFOiEnIurgipIBt4vCz8',
    appId: '1:463099747442:web:71e9a7874376da2a9a76eb',
    messagingSenderId: '463099747442',
    projectId: 'chatapp-7ceab',
    authDomain: 'chatapp-7ceab.firebaseapp.com',
    storageBucket: 'chatapp-7ceab.appspot.com',
    measurementId: 'G-0C2KKZ6739',
  );
}
